name: Python Code Format Check

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install black
        
    - name: Check and fix code formatting with black
      run: |
        black --check .  # Check code formatting with black (no changes)

