name: Python Code Format Check

on:
  push:
    branches:
      - main 

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Check code formatting with flake8
      run: |
        flake8 --count .  # Check for PEP8 compliance

    - name: Check and fix code formatting with black
      run: |
        black --check .  # Check code formatting with black (no changes)
